 -- Active: 1770210803187@@127.0.0.1@3306@aloha
DROP TABLE IF EXISTS `users`;
CREATE TABLE users (
    `no` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `id` VARCHAR(64) UNIQUE NOT NULL,
    `email` VARCHAR(255) NOT NULL UNIQUE,
    `password` VARCHAR(255) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
);